//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// RCT3D.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDD_FORM_INFO                   106
#define IDC_PREVIEW                     107
#define IDS_WINDOWS_MANAGER             107
#define IDC_SEPARATOR_1                 108
#define IDC_TEXT1                       109
#define IDC_SEPARATOR_2                 110
#define IDC_TEXT2                       111
#define IDC_SEPARATOR_3                 112
#define IDC_TEXT3                       113
#define IDC_SEPARATOR_4                 114
#define IDC_SEPARATOR_5                 115
#define IDC_TEXT4                       116
#define IDR_MAINFRAME                   128
#define IDR_RCT3DTYPE                   129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDR_POPUP_MDITABS               132
#define IDR_POPUP_DROP_MDITABS          133
#define IDR_PASTE_MENU                  134
#define IDR_WINDOWS_MENU                135
#define IDR_THEME_MENU                  136
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR_HC                  151
#define IDB_RIBBON_FILELARGE            156
#define IDB_RIBBON_DISPLAY_OPTIONS      160
#define IDI_RIBBON_DISPLAY_OPTIONS      161
#define IDR_PROPERTIES                  162
#define IDB_PROPERTIES_HC               163
#define IDB_MODEL_BROWSER_BEGIN         360
#define IDB_MB_UNKNOWN                  360
#define IDB_MODEL_FILE                  361
#define IDB_PRODUCT_STRUCTURE_1         362
#define IDB_PRODUCT_STRUCTURE_2         363
#define IDB_RI_SOLID                    364
#define IDB_RI_SURFACE                  365
#define IDB_RI_PLANE                    366
#define IDB_RI_LINE                     367
#define IDB_RI_ARC                      368
#define IDB_RI_COMP_CURVE               369
#define IDB_RI_CURVE                    370
#define IDB_RI_POINT                    371
#define IDB_RI_POINT_CLOUD              372
#define IDB_RI_DIRECTION                373
#define IDB_RI_COORD_SYS                374
#define IDB_RI_GEOMETRY_SET             375
#define IDB_VIEW                        376
#define IDB_ANNOTATION_VIEW             377
#define IDB_VIEW_GROUP                  378
#define IDB_PMI_TEXT                    379
#define IDB_PMI_TOLERANCE               380
#define IDB_PMI_DIM_DISTANCE            381
#define IDB_PMI_DIM_LENGTH              382
#define IDB_PMI_DIM_RADIUS              383
#define IDB_PMI_DIM_DIAMETER            384
#define IDB_PMI_DIM_ANGLE               385
#define IDB_PMI_DATUM                   386
#define IDB_PMI_DATUM_TARGET            387
#define IDB_PMI_ROUGHNESS               388
#define IDB_PMI_CIRCLE_CENTER           389
#define IDB_PMI_LINE_WELDING            390
#define IDB_PMI_SPOT_WELDING            391
#define IDB_PMI_BALLOON                 392
#define IDB_PMI_COORDINATE              393
#define IDB_PMI_FASTENER                394
#define IDB_PMI_LOCATOR                 395
#define IDB_PMI_MEASUREMENT_POINT       396
#define IDB_PMI_ARROW                   397
#define IDB_PMI_TABLE                   398
#define IDB_PMI_GROUP                   399
#define IDB_DRW_MODEL                   400
#define IDB_DRW_SHEET                   401
#define IDB_DRW_VIEW                    402
#define IDB_DRW_VIEW_BACK               403
#define IDB_DRW_VIEW_BACKGROUND         404
#define IDB_DRW_VIEW_BOTTOM             405
#define IDB_DRW_VIEW_DETAIL             406
#define IDB_DRW_VIEW_FRONT              407
#define IDB_DRW_VIEW_ISO                408
#define IDB_DRW_VIEW_LEFT               409
#define IDB_DRW_VIEW_RIGHT              410
#define IDB_DRW_VIEW_SECTION            411
#define IDB_DRW_VIEW_TOP                412
#define IDB_MODEL_BROWSER_END           412
#define IDD_EXCHANGE_IMPORT_DIALOG      415
#define IDC_PROGRESS_BAR                1000
#define IDC_EDIT_MESSAGES               1007
#define IDC_IMPORT_MESSAGE              1008
#define IDC_CHECK_KEEP_OPEN             1009
#define IDC_COMPANY_URL                 1041
#define IDC_INFO_LABEL                  1042
#define IDC_PATH_LABEL                  1043
#define IDC_BUTTON1                     1044
#define IDC_BUTTON2                     1045
#define IDC_BUTTON3                     1046
#define IDC_DOC_NAME                    1047
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_WORKSPACE               32791
#define ID_VIEW_WORKSPACE2              32792
#define ID_VIEW_OUTPUT                  32803
#define ID_TOOLS_ENTRY                  32804
#define ID_USER_TOOL1                   32805
#define ID_USER_TOOL2                   32806
#define ID_USER_TOOL3                   32807
#define ID_USER_TOOL4                   32808
#define ID_USER_TOOL5                   32809
#define ID_USER_TOOL6                   32810
#define ID_USER_TOOL7                   32811
#define ID_USER_TOOL8                   32812
#define ID_USER_TOOL9                   32813
#define ID_USER_TOOL10                  32814
#define ID_TOOLS_MANAGER                32815
#define ID_WINDOW_MANAGER               32825
#define ID_VIEW_APPLOOK                 32826
#define ID_VIEW_PROPERTIES              32827
#define ID_MDI_NEW_VERT_GROUP           32828
#define ID_MDI_NEW_HORZ_TAB_GROUP       32829
#define ID_MDI_MOVE_TO_PREV_GROUP       32830
#define ID_MDI_CANCEL                   32831
#define ID_MDI_MOVE_TO_NEXT_GROUP       32832
#define ID_TOOLS_OPTIONS                32833
#define ID_RIBBON_AUTOHIDE              32834
#define ID_RIBBON_SHOW_TABS             32835
#define ID_RIBBON_SHOW_TABS_COMMANDS    32836
#define ID_STATUSBAR_PANE1              32837
#define ID_STATUSBAR_PANE2              32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
