#define COMMAND_START 20000

#define FILE_3D_CAT                                       20001
#define FILE_3D_PNL_Open                                  20002
#define FILE_3D_CMD_New                                   20003
#define FILE_3D_CMD_Open                                  20004
#define FILE_3D_CMD_Insert                                20005
#define FILE_3D_PNL_Save                                  20006
#define FILE_3D_CMD_Save                                  20007
#define FILE_3D_CMD_SaveAs                                20008
#define FILE_3D_CMD_Export                                20009
#define FILE_3D_CMD_Print                                 20010
#define FILE_3D_PNL_Settings                              20011
#define FILE_3D_CMD_Options                               20012
#define FILE_3D_CMD_Close                                 20013
#define HOME_3D_CAT                                       20014
#define HOME_3D_PNL_Panels                                20015
#define HOME_3D_CMD_Panels_Model                          20016
#define HOME_3D_CMD_Panels_View                           20017
#define HOME_3D_CMD_Panels_Layer                          20018
#define HOME_3D_CMD_Panels_Scene                          20019
#define HOME_3D_PNL_Focus                                 20020
#define HOME_3D_CMD_Pan                                   20021
#define HOME_3D_LST_Zoom                                  20022
#define HOME_3D_CMD_Zoom_Fit                              20023
#define HOME_3D_CMD_Zoom_Area                             20024
#define HOME_3D_CMD_Zoom_Object                           20025
#define HOME_3D_LST_Rotate                                20026
#define HOME_3D_CMD_Rotate_Rotate                         20027
#define HOME_3D_CMD_Rotate_RotateCenter                   20028
#define HOME_3D_CMD_Rotate_Turntable                      20029
#define HOME_3D_CMD_Rotate_Orbit                          20030
#define HOME_3D_PNL_View                                  20031
#define HOME_3D_LST_ViewStyle                             20032
#define HOME_3D_CMD_ViewStyle_Shade                       20033
#define HOME_3D_CMD_ViewStyle_ShadeWithEdges              20034
#define HOME_3D_CMD_ViewStyle_Wireframe                   20035
#define HOME_3D_CMD_ViewStyle_HiddenLineRemove            20036
#define HOME_3D_CMD_ViewStyle_Tessellated                 20037
#define HOME_3D_LST_ViewDirection                         20038
#define HOME_3D_CMD_ViewDirection_Top                     20039
#define HOME_3D_CMD_ViewDirection_Front                   20040
#define HOME_3D_CMD_ViewDirection_Left                    20041
#define HOME_3D_CMD_ViewDirection_Bottom                  20042
#define HOME_3D_CMD_ViewDirection_Back                    20043
#define HOME_3D_CMD_ViewDirection_Right                   20044
#define HOME_3D_CMD_ViewDirection_Iso                     20045
#define HOME_3D_CMD_ViewDirection_SeIso                   20046
#define HOME_3D_CMD_ViewDirection_Perspective             20047
#define HOME_3D_LST_Visualize                             20048
#define HOME_3D_CMD_Visualize_ShowAll                     20049
#define HOME_3D_CMD_Visualize_Hide                        20050
#define HOME_3D_CMD_Visualize_ShowOnly                    20051
#define HOME_3D_CMD_Visualize_Toggle                      20052
#define HOME_3D_CMD_Visualize_Reset                       20053
#define HOME_3D_LST_VisualEffects                         20054
#define HOME_3D_CMD_VisualEffects_Shadow                  20055
#define HOME_3D_CMD_VisualEffects_Reflection              20056
#define HOME_3D_CMD_VisualEffects_AmbientOcclusion        20057
#define HOME_3D_CMD_VisualEffects_SilhouetteEdges         20058
#define HOME_3D_CMD_VisualEffects_Bloom                   20059
#define HOME_3D_PNL_SelectAndSnap                         20060
#define HOME_3D_LST_Select                                20061
#define HOME_3D_CMD_Select_All                            20062
#define HOME_3D_CMD_Select_Deselect                       20063
#define HOME_3D_CMD_Select_Point                          20064
#define HOME_3D_CMD_Select_Curve                          20065
#define HOME_3D_CMD_Select_Plane                          20066
#define HOME_3D_CMD_Select_Surface                        20067
#define HOME_3D_CMD_Select_Solid                          20068
#define HOME_3D_CMD_Select_Section                        20069
#define HOME_3D_CMD_Select_Text                           20070
#define HOME_3D_CMD_Select_Dimension                      20071
#define HOME_3D_CMD_Select_Axis                           20072
#define HOME_3D_POP_SelectionFiter                        20073
#define HOME_3D_CMD_SelectionFiter_Point                  20074
#define HOME_3D_CMD_SelectionFiter_Curve                  20075
#define HOME_3D_CMD_SelectionFiter_Edge                   20076
#define HOME_3D_CMD_SelectionFiter_Face                   20077
#define HOME_3D_CMD_SelectionFiter_Solid                  20078
#define HOME_3D_CMD_SelectionFiter_Axis                   20079
#define HOME_3D_CMD_SelectionFiter_PMI                    20080
#define HOME_3D_POP_ObjectSnap                            20081
#define HOME_3D_CMD_ObjectSnap_Point                      20082
#define HOME_3D_CMD_ObjectSnap_End                        20083
#define HOME_3D_CMD_ObjectSnap_Mid                        20084
#define HOME_3D_CMD_ObjectSnap_Intersection               20085
#define HOME_3D_CMD_ObjectSnap_Perpendicular              20086
#define HOME_3D_CMD_ObjectSnap_Center                     20087
#define HOME_3D_CMD_ObjectSnap_Quadrant                   20088
#define HOME_3D_CMD_ObjectSnap_Near                       20089
#define HOME_3D_CMD_ObjectSnap_OnSurface                  20090
#define HOME_3D_CMD_ObjectSnap_BoundaryCenter             20091
#define HOME_3D_CMD_ObjectSnap_Axis                       20092
#define HOME_3D_CMD_ObjectSnap_Absolute                   20093
#define HOME_3D_CMD_ObjectSnap_Relative                   20094
#define HOME_3D_CMD_ObjectSnap_ExpandLine                 20095
#define HOME_3D_PNL_Window                                20096
#define HOME_3D_CMD_Window_Cascade                        20097
#define HOME_3D_CMD_Window_TileHorizontal                 20098
#define HOME_3D_CMD_Window_TileVertical                   20099
#define MEASURE_3D_CAT                                    20100
#define MEASURE_3D_PNL_Basic                              20101
#define MEASURE_3D_CMD_Basic_Coordinate                   20102
#define MEASURE_3D_CMD_Basic_Distance                     20103
#define MEASURE_3D_CMD_Basic_Length                       20104
#define MEASURE_3D_CMD_Basic_Radius                       20105
#define MEASURE_3D_CMD_Basic_Angle                        20106
#define MEASURE_3D_PNL_Physical                           20107
#define MEASURE_3D_CMD_Physical_BoundBox                  20108
#define MEASURE_3D_CMD_Physical_Area                      20109
#define MEASURE_3D_CMD_Physical_VolumnWeight              20110
#define MEASURE_3D_CMD_Physical_CenterOfGravity           20111
#define MEASURE_3D_CMD_Physical_ProjectionArea            20112
#define MEASURE_3D_PNL_Annotation                         20113
#define MEASURE_3D_CMD_Annotation                         20114
#define MEASURE_3D_PNL_Settings                           20115
#define MEASURE_3D_CMD_Settings                           20116
#define ANALYZE_3D_CAT                                    20117
#define SECTION_3D_CAT                                    20118
#define AXIS_3D_CAT                                       20119
#define TRANSFORM_3D_CAT                                  20120
#define TOOLS_3D_CAT                                      20121
#define CREATE_3D_CAT                                     20122
#define EDIT_3D_CAT                                       20123
#define TOOLBAR_3D_CAT                                    20124
#define TOOLBAR_3D_PNL_Layer                              20125
#define TOOLBAR_3D_PNL_Model                              20126
#define TOOLBAR_3D_LST_Sort                               20127
#define TOOLBAR_3D_CMD_Sort_ByOriginal                    20128
#define TOOLBAR_3D_CMD_Sort_ByAscending                   20129
#define TOOLBAR_3D_CMD_Sort_ByDescending                  20130
#define TOOLBAR_3D_CMD_Option_CheckBoxes                  20131
#define TOOLBAR_3D_CMD_Option_GridLines                   20132
#define TOOLBAR_3D_CMD_Option_AlternateRows               20133
#define CUSTOM_3D_CAT                                     20134
#define CUSTOM_3D_PNL_SYSONG                              20135
#define CUSTOM_3D_CMD_SYSONG_Test1                        20136
#define CUSTOM_3D_CMD_SYSONG_Test2                        20137
#define CUSTOM_3D_CMD_SYSONG_Test3                        20138
#define CUSTOM_3D_CMD_SYSONG_Test4                        20139
#define CUSTOM_3D_CMD_SYSONG_Test5                        20140
#define CUSTOM_3D_CMD_SYSONG_Test6                        20141
#define CUSTOM_3D_CMD_SYSONG_Test7                        20142
#define CUSTOM_3D_CMD_SYSONG_Test8                        20143
#define CUSTOM_3D_CMD_SYSONG_Test9                        20144
#define CUSTOM_3D_PNL_KEN                                 20145
#define CUSTOM_3D_CMD_KEN_Test1                           20146
#define CUSTOM_3D_CMD_KEN_Test2                           20147
#define CUSTOM_3D_CMD_KEN_Test3                           20148
#define CUSTOM_3D_CMD_KEN_Test4                           20149
#define CUSTOM_3D_CMD_KEN_Test5                           20150
#define CUSTOM_3D_CMD_KEN_Test6                           20151
#define CUSTOM_3D_CMD_KEN_Test7                           20152
#define CUSTOM_3D_CMD_KEN_Test8                           20153
#define CUSTOM_3D_CMD_KEN_Test9                           20154
#define HOME_2D_CAT                                       20155
#define HOME_2D_PNL_Panels                                20156
#define HOME_2D_CMD_Panels_Model                          20157
#define HOME_2D_CMD_Panels_View                           20158
#define HOME_2D_CMD_Panels_Layer                          20159
#define HOME_2D_PNL_Focus                                 20160
#define HOME_2D_CMD_Pan                                   20161
#define HOME_2D_LST_Zoom                                  20162
#define HOME_2D_CMD_Zoom_Fit                              20163
#define HOME_2D_CMD_Zoom_Area                             20164
#define HOME_2D_POP_ObjectSnap                            20165
#define HOME_2D_CMD_ObjectSnap_Point                      20166
#define HOME_2D_CMD_ObjectSnap_End                        20167
#define HOME_2D_CMD_ObjectSnap_Mid                        20168
#define HOME_2D_CMD_ObjectSnap_Intersection               20169
#define HOME_2D_CMD_ObjectSnap_Perpendicular              20170
#define HOME_2D_CMD_ObjectSnap_Center                     20171
#define HOME_2D_CMD_ObjectSnap_Quadrant                   20172
#define HOME_2D_CMD_ObjectSnap_Near                       20173
#define HOME_2D_LST_Select                                20174
#define HOME_2D_CMD_Select_Point                          20175
#define HOME_2D_PNL_Window                                20176
#define HOME_2D_CMD_Window_Cascade                        20177
#define HOME_2D_CMD_Window_TileHorizontal                 20178
#define HOME_2D_CMD_Window_TileVertical                   20179
#define EDIT_2D_CAT                                       20180
#define EDIT_2D_PNL_History                               20181
#define EDIT_2D_CMD_Undo                                  20182
#define EDIT_2D_CMD_Redo                                  20183
#define DRAW_2D_CAT                                       20184
#define DRAW_2D_PNL_Basic                                 20185
#define DRAW_2D_LST_Point                                 20186
#define DRAW_2D_CMD_Point                                 20187
#define DRAW_2D_CMD_Divide                                20188
#define DRAW_2D_LST_Line                                  20189
#define DRAW_2D_CMD_Line                                  20190
#define DRAW_2D_CMD_Polyline                              20191
#define DRAW_2D_CMD_Rectangle                             20192
#define DRAW_2D_CMD_Polygon                               20193
#define DRAW_2D_LST_Circle                                20194
#define DRAW_2D_CMD_Circle_2Points                        20195
#define DRAW_2D_CMD_Circle_3Points                        20196
#define DRAW_2D_CMD_Circle_CenterRadius                   20197
#define DRAW_2D_CMD_Circle_2TangentsRadius                20198
#define DRAW_2D_LST_Arc                                   20199
#define DRAW_2D_CMD_Arc_3Points                           20200
#define DRAW_2D_CMD_Arc_CenterStartEnd                    20201
#define DRAW_2D_CMD_Arc_2TangentsRadius                   20202
#define DRAW_2D_LST_Ellipse                               20203
#define DRAW_2D_CMD_Ellipse_2Axes                         20204
#define DRAW_2D_CMD_Ellipse_Center2Axes                   20205
#define DRAW_2D_LST_EllipticalArc                         20206
#define DRAW_2D_CMD_EllipticalArc_2Axes                   20207
#define DRAW_2D_CMD_EllipticalArc_Center2Axes             20208
#define DRAW_2D_CMD_Spline                                20209
#define DRAW_2D_PNL_Annotate                              20210
#define DRAW_2D_CMD_Text                                  20211
#define CONTEXT_2D_START                                  20212
#define CONTEXT_2D_POP_ObjectSnap_Overrides               20213
#define CONTEXT_2D_CMD_ObjectSnap_Point                   20214
#define CONTEXT_2D_CMD_ObjectSnap_End                     20215
#define CONTEXT_2D_CMD_ObjectSnap_Mid                     20216
#define CONTEXT_2D_CMD_ObjectSnap_Intersection            20217
#define CONTEXT_2D_CMD_ObjectSnap_Perpendicular           20218
#define CONTEXT_2D_CMD_ObjectSnap_Center                  20219
#define CONTEXT_2D_CMD_ObjectSnap_Quadrant                20220
#define CONTEXT_2D_CMD_ObjectSnap_Near                    20221
#define CONTEXT_2D_CMD_Enter                              20222
#define CONTEXT_2D_CMD_Cancel                             20223
#define CONTEXT_2D_CMD_Undo                               20224
#define CONTEXT_2D_CMD_Close                              20225
#define CONTEXT_2D_END                                    20226

#define COMMAND_END 20227


